apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_PORT: "3000"
  DB_HOST: "banco-service" # Aponta para o Service K8s do PostgreSQL
  DB_PORT: "5432"
  DB_NAME: "oficina_mvp"
  JWT_EXPIRES_IN_MINUTES: "30"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000"
  SEED_ADMIN_EMAIL: "admin@oficina.com"
  MAIL_USERNAME: "${MAIL_USERNAME}"
  MAIL_FROM: "${MAIL_FROM}"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: "oficina"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SEED_ADMIN_PASSWORD: "${SEED_ADMIN_PASSWORD}"
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
